birzum/apps/blog/urls.py
from django.urls import path

from .views import detail_view, list_view

app_name = "blog"

urlpatterns = [
    path("", list_view, name="list"),
    path("<slug:slug>/", detail_view, name="detail")
]

birzum/apps/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
    path('clear/', views.cart_clear, name='clear'),
    path('update/', views.update, name='update')
]

birzum/users/urls.py
from django.urls import path

from birzum.users.views import user_address_update_view, user_address_create_view,user_redirect_view, user_update_view, user_account_dashboard_view, user_account_addresses_view, user_account_orders_view, user_account_detail_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/detail/", view=user_account_dashboard_view, name="detail"),

    path("<str:username>/account_details/", view = user_account_detail_view, name="account_details"),
    path("<str:username>/account_details_update/", view=user_update_view, name="account_details_update"),

    path("<str:username>/account_orders/", view=user_account_orders_view, name="account_orders"),

    path("<str:username>/account_addresses/", view = user_account_addresses_view, name="account_addresses"),
    path("account_addresses/create/", view = user_address_create_view, name="address_create"),
    path("<str:username>/address/<int:pk>/change/", view = user_address_update_view, name="address_change"),
]

config/urls.py
"use client";

import Link, { LinkProps } from "next/link";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

type AnchorProps = ComponentPropsWithoutRef<"a">;

type Props = AnchorProps & LinkProps & {
  className?: string;
  children: ReactNode;
};

urlpatterns = (
    i18n_patterns(
        path("", HomeView.as_view(), name="home"),
        path("coming-soon/", TemplateView.as_view(template_name="pages/soon.html"), name="soon"),
        # Django Admin, use {% url 'admin:index' %}
        path(settings.ADMIN_URL, admin.site.urls),
        path("translations/", include("rosetta.urls")),
        # path("hijack", include('hijack.urls', namespace='hijack')),
        # User management
        path("users/", include("birzum.users.urls", namespace="users")),
        path("accounts/login/", user_login_view, name="account_login"),
        path("accounts/signup/", user_signup_view, name="account_signup"),
        path("accounts/", include("allauth.urls")),
        path('ckeditor/', include('ckeditor_uploader.urls')),
        # Your stuff: custom urls includes go here
        path("cart/", include('birzum.apps.cart.urls', namespace='cart')),
        path("blog/", include('birzum.apps.blog.urls', namespace='blog')),
        path("whishlist/", include('birzum.apps.smallapps.whishlist.urls', namespace='whishlist')),
        path("compare/", include('birzum.apps.smallapps.compare.urls', namespace='compare')),
        path("company/", include('birzum.apps.smallapps.company.urls', namespace='company')),
        path("order/", include('birzum.apps.order.urls', namespace='order')),
        path("rate/", include('birzum.apps.smallapps.rating.urls', namespace='rating')),
        path("", include('birzum.apps.products.urls', namespace="products")),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

birzum/apps/cart/models.py
# from django.db import models

# # Create your models here.

birzum/apps/smallapps/manuals/models.py
from django.db import models
from model_utils.models import TimeStampedModel

# class Shipping(TimeStampedModel):
#     pass


# class TakeBackProducts(TimeStampedModel):
#     pass


# class LisingRules(TimeStampedModel):
#     pass


# class FoydalanishShartlari(TimeStampedModel):
#     pass

birzum/apps/smallapps/company/forms.py
import re

from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Message
        fields = ['name', 'phone', 'message']

birzum/apps/blog/views.py
from django.views.generic import ListView, DetailView

from .models import New

# Create your views here.
class BlogListView(ListView):
    model = New

    def get_queryset(self):
        qs =  super().get_queryset()
        q = self.request.GET.get('q', None)
        discount = self.request.GET.get('discount', None)
        new = self.request.GET.get('new', None)
        if q:
            qs = qs.filter(title__icontains=q)
        if discount:
            qs = qs.filter(stock=True)
        if new:
            qs = qs.filter(news=True)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news"] = New.objects.all().order_by('-created')[:6]
        return context
    


list_view = BlogListView.as_view()


class BlogDetailView(DetailView):
    model = New
    slug_field = "slug"


detail_view = BlogDetailView.as_view()

birzum/apps/cart/views.py
from django.core.checks import messages
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

from birzum.apps.products.models import Product

from .cart import Cart


def cart_add(request, id):
    # xaridorga ko'rasiladigon xabarlar
    success_message = _("Mahsulot muvoffaqiyatli qo'shildi!")
    fail_message = _("Mahsulot sotuvda qolmagan!")

    cart = Cart(request)
    count = request.GET.get('count', 1)
    obj = Product.objects.filter(available=True, id=id).first()

    # agar product bor bo'lsa get parametrdan uni countini tekshirib ko'ramiz
    if obj:
        # tekshiruv tugagandan song cartaga mahsulotni qo'shib yuboramiz
        cart.add(product=obj, quantity=int(count))

        return JsonResponse({"success": True, "message": success_message, 'count': count}, safe=False)
    return JsonResponse({"success": False, "message": fail_message}, safe=False)


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})


def update(request):
    cart = Cart(request)
    count = request.GET.get('quantity')
    id = int(request.GET.get('id'))

    obj = Product.objects.filter(available=True, id=id).first()

    if obj:
        if obj.id in [int(item) for item in cart.cart.keys()]:
            cart.cart[str(obj.id)]['quantity'] = int(count)
            cart.cart[str(obj.id)]['price'] = str(obj.price * int(count))
            cart.save()
            data = {'product_price': obj.price * int(count), "total_price": cart.get_total_price()}
            return JsonResponse(data)
        else:
            cart.add(product=obj, quantity=int(count))
            data = {'product_price': obj.price * int(count), "total_price": cart.get_total_price()}
            return JsonResponse(data)

    return JsonResponse({"success": False})

birzum/apps/order/views.py
from django.urls import reverse
from django.views.generic import CreateView, TemplateView

from birzum.apps.cart.cart import Cart

from .models import Order
from .utils import create_order_items


# Create your views here.
class OrderCreate(CreateView):
    model = Order

    fields = [
        'first_name', 'last_name', 'region', 'district', 'house',
        'street', 'postcode', 'phone', 'message'
        ]

    template_name = 'order/order_create.html'

    def form_valid(self, form):
        cart = Cart(self.request)
        if form.is_valid:
            extra = self.request.POST
            obj = form.save()
            obj.payment = extra.get('payment-method', '')
            obj.shipping = extra.get('shipping-method', '')
            obj.save()
            create_order_items(obj=obj, cart=cart, request=self.request)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("order:success")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart"] = Cart(self.request)
        return context
    

order_create_view = OrderCreate.as_view()


class OrderSucceeded(TemplateView):
    template_name = "order/success.html"


order_succeeded_view = OrderSucceeded.as_view()

birzum/apps/products/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView
from django_filters.views import FilterView
from django.core.paginator import Paginator

from birzum.apps.smallapps.company.models import Features
from birzum.apps.smallapps.rating.models import Rating
from .models import Category, Product, Brand
from .filters import ProductFilter
from .last_seen import Last
# Create your views here.


class Home(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        last = Last(self.request)
        ctx['categories'] = Category.objects.select_related('parent')
        ctx['last_seen'] = Product.objects.filter(id__in=last.box.keys()).prefetch_related('images')
        return ctx


home_view = Home.as_view()


class ProductList(FilterView):
    queryset = Product.objects.select_related('category', 'brand', 'chegirma').prefetch_related('image', 'ratings')
    filterset_class = ProductFilter
    paginate_by = 30

    def get_queryset(self, **kwargs):
        cat_slug = self.kwargs.get('cat_slug', None)
        paginate = self.request.GET.get('paginate', 9)
        self.paginate_by = paginate
        if cat_slug:
            categories = get_object_or_404(Category, slug=cat_slug)
        try:
            return self.queryset.filter(
                category__in=categories.get_descendants(include_self=True)
                )
        except Exception as e:
            return self.queryset

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['brands'] = Brand.objects.select_related('category').prefetch_related('product').all()
        ctx['cats'] = Category.objects.filter(image__isnull=False).select_related('parent')
        return ctx


product_list_view = ProductList.as_view()


class ProductDetail(DetailView):
    queryset = Product.objects.select_related(
        'category', 'brand', 'chegirma').prefetch_related('image', 'ratings').all()
    slug_field = 'slug'
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['categories'] = Category.objects.select_related('parent').all()
        return ctx

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["features"] = Features.objects.all()
        if self.object.brand:
            context["products_from_this_vendor"] = Product.items.in_same_vendor(
                brand_id=self.object.brand.id, prod_id=self.object.id)
        context["products_in_this_cat"] = Product.items.in_same_category(
            cat_id=self.object.category_id, prod_id=self.object.id)
        context["more"] = Product.items.more()
        context["comments"] = Rating.objects.select_related('product').filter(
            product=self.object, published=True)
        return context

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        last_seen = Last(self.request)
        last_seen.add(product_id=obj.id)
        return obj


product_detail_view = ProductDetail.as_view()

birzum/apps/smallapps/company/views.py
from django.views.generic import DetailView, CreateView
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.urls import reverse 

from birzum.apps.blog.models import Savollar
from .models import AboutUs, Leaders, Awards, Contact, Message
from .forms import MessageForm


class About(DetailView):
    model = AboutUs
    template_name = "pages/about.html"

    def get_queryset(self):
        return super().get_queryset()
    
    def get_object(self):
        qs = self.get_queryset()
        return qs.first()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["leaders"] = Leaders.objects.all()
        context["awards"] = Awards.objects.all()
        return context
    
    
about_view = About.as_view()


class ContactUs(CreateView):
    model = Message
    template_name = "pages/contact.html"
    form_class = MessageForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["questions"] = Savollar.objects.all()
        context["contact"] = Contact.objects.first()
        return context

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, _("Sizning xabaringiz yuborildi"))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.WARNING, _("Quyidagi xatolarni to'g'irlang!"))
        return super().form_invalid(form)

    def get_succes_url(self):
        return reverse('company:contact')


contact_view = ContactUs.as_view()

birzum/apps/smallapps/compare/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _

from birzum.apps.products.models import Product 
from .compare import Compare


def compare_add(request, id):
    # xaridorga ko'rasiladigon xabarlar
    success_message = _("Mahsulot muvoffaqiyatli qo'shildi!")
    fail_message = _("Mahsulot sotuvda qolmagan!")

    compare = Compare(request)
    obj = Product.objects.filter(id=id).first()

    # agar product bor bo'lsa get parametrdan uni countini tekshirib ko'ramiz
    if obj:
        print("Compareaga qoshildi")
        # tekshiruv tugagandan song compareaga mahsulotni qo'shib yuboramiz
        compare.add(str(obj.id))

        return JsonResponse({"success": True, "message": success_message}, safe=False)

    return JsonResponse({"success": False, "message": fail_message}, safe=False)


def compare_remove(request, product_id):
    compare = Compare(request)
    product = get_object_or_404(Product, id=product_id)
    compare.remove(str(product.id))
    return redirect('compare:compare')


def compare_clear(request):
    compare = Compare(request)
    compare.clear()
    return redirect('compare:compare')


def compare_detail(request):
    compare = Compare(request)
    products = Product.objects.filter(id__in=compare.compare.keys())
    return render(request, 'smallapps/compare/compare.html', {'products': products})

birzum/apps/smallapps/rating/views.py
from django.contrib import messages
from django.db.models import Avg
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.utils.translation import gettext_lazy as _

from birzum.apps.products.models import Product
from .models import Rating
# Create your views here.


def rate(request, id):
    rating = request.POST.get('review[rating]', 0)
    message = request.POST.get('message', "")
    phone = request.POST.get('phone', "")
    name = request.POST.get('name', "")

    print(rating, message, phone, name)
    product = get_object_or_404(Product, id=id)
    if product:
        Rating.objects.create(
            product=product, rate=int(rating), comment=message,
            person=name, contact=phone
            )

        messages.add_message(request, messages.SUCCESS, _("Mahsulotga baho berganingizdan mamnunmiz!"))

    ratings = Rating.objects.filter(product=product)
    overall = int(round(ratings.aggregate(Avg('rate'))['rate__avg']))
    product.rating = overall
    product.save()

    return redirect('products:detail', cat_slug=product.category.slug, slug=product.slug)

birzum/templates/smallapps/whishlist/whishlist.html
{% extends 'base.html' %}
{% load static i18n custom_tags humanize %}


{% block content %}
{% include 'includes/home_header.html' %}
<!-- Start of Main -->
<main class="main wishlist-page">
    <!-- Start of Page Header -->
    <div class="page-header">
        <div class="container">
            <h1 class="page-title mb-0">{% trans "Sevimli mahsulotlar" %}</h1>
        </div>
    </div>
    <!-- End of Page Header -->

    <!-- Start of Breadcrumb -->
    <nav class="breadcrumb-nav mb-10">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home' %}">{% trans "Asosiy sahifa" %}</a></li>
                <li>{% trans "Sevimli mahsulotlar" %}</li>
            </ul>
        </div>
    </nav>
    <!-- End of Breadcrumb -->

    <!-- Start of PageContent -->
    <div class="page-content">
        <div class="container">
            <h3 class="wishlist-title">{% trans "Mahsulotlar" %}</h3>
            {% if products|length > 0 %}
            <table class="shop-table wishlist-table">
                <thead>
                    <tr class="text-left">
                        <th class="product-name"><span>Product</span></th>
                        <th></th>
                        <th class="product-price"><span>Price</span></th>
                        <th class="product-stock-status"><span>Stock Status</span></th>
                        <th class="wishlist-action">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in products %}
                    <tr>
                        <td class="product-thumbnail">
                            <div class="p-relative">
                                <a href="{% url 'whishlist:remove' product_id=item.id %}">
                                    <figure>
                                        <img src="{{ item.get_first_image.url }}" alt="product" width="300"
                                            height="338">
                                    </figure>
                                </a>
                                <button type="submit" class="btn btn-close"><i
                                        class="fas fa-times"></i></button>
                            </div>
                        </td>
                        <td class="product-name">
                            <a href="{{ item.get_absolute_url }}">
                                {{ item.title }}
                            </a>
                        </td>
                        <td class="product-price">
                            {% if item.discount %}
                            <ins class="new-price">{{ item.discount_price|sum|floatformat:-2|intcomma }} UZS</ins> <br>
                            <del class="old-price">{{ item.price|sum|floatformat:-2|intcomma }} UZS</del>
                            {% else %}
                            <ins class="new-price">{{ item.price|sum|floatformat:-2|intcomma }} UZS</ins>
                            {% endif %}
                        </td>
                        <td class="product-stock-status">
                            {% if item.available %}
                            <span class="wishlist-in-stock">{% trans "Sotuvda mavjud" %}</span> <br>
                            {% endif %}
                            {% if item.bestseller %}
                            <span class="wishlist-in-stock">{% trans "Bestseller" %}</span><br>
                            {% endif %}
                            {% if item.discount %}
                            <span class="wishlist-in-stock">{% trans "Chegirmada" %}</span><br>
                            {% endif %}
                            {% if item.lising %}
                            <span class="wishlist-in-stock">{% trans "Lisingga mavjud" %}</span>
                            {% endif %}
                        </td>
                        <td class="wishlist-action">
                            <div class="d-lg-flex">
                                <a href="{% url 'cart:add' id=item.id %}" class="btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart">{% trans "Savatga qo'shish" %}</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="text-center">
                <h4 class="mt-5 mb-3">{% trans "Sevimli mahsulotlar hozircha yo'q" %}</h4>
                <a href="{% url 'products:list' %}" class="btn btn-primary">{% trans "Mahsulotlar" %}</a>
            </div>
            {% endif %}
            <div class="social-links">
                <label>{% trans "Do'stlar bilan ulashing:" %}</label>
                <div class="social-icons social-no-color border-thin">
                    <a href="#" class="social-icon social-facebook w-icon-facebook"></a>
                    <a href="#" class="social-icon social-twitter w-icon-twitter"></a>
                    <a href="#" class="social-icon social-pinterest w-icon-pinterest"></a>
                    <a href="#" class="social-icon social-email far fa-envelope"></a>
                    <a href="#" class="social-icon social-whatsapp fab fa-whatsapp"></a>
                </div>
            </div>
        </div>
    </div>
    <!-- End of PageContent -->
</main>
<!-- End of Main -->

{% endblock content %}